services:
  liberstack-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: liberstack-fastapi-prod
    
    restart: unless-stopped
    
    ports:
      - "8000:8000"
    env_file:
      - .env  
    
    networks:
      - liberstack-network
      
    # limiting de logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    # monitor de saude da api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

networks:
  liberstack-network:
    driver: bridge